repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]  # автоматически исправляет ошибки линтера
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]
